---
Name: menu-manager-subsites
---

Heyday\MenuManager\MenuItem:
  extensions:
    - Guttmann\SilverStripe\MenuItemExtension
Heyday\MenuManager\MenuSet:
  extensions:
    - Guttmann\SilverStripe\MenuSetExtension
Heyday\MenuManager\MenuAdmin:
  extensions:
    - SilverStripe\Subsites\Extensions\SubsiteMenuExtension
    - Guttmann\SilverStripe\MenuAdminExtension
Heyday\MenuManager\MenuManagerTemplateProvider:
  extensions:
    - Guttmann\SilverStripe\MenuManagerTemplateProviderExtension
